# Default values for prometheus-to-cloudwatch
image:
  repository: cloudposse/prometheus-to-cloudwatch
  tag: 0.1.0
  pullPolicy: IfNotPresent
service:
  port: 8080
  # Default to clusterIP for backward compatibility
  type: ClusterIP
  nodePort: 0
  loadBalancerIP: ""
rbac:
  # If true, create & use RBAC resources
  create: false
  # Ignored if rbac.create is true
  serviceAccountName: default

## Node labels for pod assignment
## Ref: https://kubernetes.io/docs/user-guide/node-selection/
nodeSelector: {}

# Annotations to be added to the pod
podAnnotations: {}
