apiVersion: v1
kind: Secret
metadata:
  name: {{ template "prometheus-to-cloudwatch.fullname" . }}
  labels:
    app: {{ template "prometheus-to-cloudwatch.name" . }}
    chart: {{ template "prometheus-to-cloudwatch.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
{{- range $name, $value := .Values.secrets }}
{{- if not (empty $value) }}
  {{ $name }}: {{ $value | b64enc }}
{{- end }}
{{- end }}
