name: Build & push flux-automation-controller image
on:
  pull_request:
  push:
    paths:
      - 'image-automation-controller/Dockerfile'
      - '.github/workflows/flux-image-automation-controller.yaml'
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    name: Build docker image
    steps:
      - uses: actions/checkout@master

      - name: 'Artifact: build && push fluxcd/image-automation-controller image'
        uses: aevea/action-kaniko@v0.10.0
        with:
          registry: artifact.onwalk.net
          username: admin
          password: ${{ secrets.HELM_REPO_PASSWORD }}
          path: ./image-automation-controller
          build_file: ./Dockerfile
          image: k8s/fluxcd/image-automation-controller
          tag: v0.24.0
          cache: true
          cache_registry: cache
